name: Playwright Tests
on:
  workflow_call:
    inputs:
      Environment:
        description: select environment
        required: false
        default: nonProd
        type: string
      github_environment:
        description: select github environment
        required: false
        type: string
        default: nonProd
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        description: select workflow environment
        required: true
        default: nonProd
        options:
          - nonProd
          - Staging       
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install browsers
      run: ./batect playwright-install    
    - name: Install dependencies
      run: ./batect install
    - name: Run Playwright tests
      run: ./batect test 
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
